version: '3.9'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - OCR_SERVICE_URL=http://ocr:7070/ocr
    depends_on:
      - mongodb
      - ocr

  ocr:
    build: ./ocr
    ports:
      - "7070:7070"

  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - backend
