name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        run: |
          docker build -t ocr-ui:latest ./frontend
          docker build -t ocr-backend:latest ./backend
          docker build -t ocr-service:latest ./ocr
          docker build -t ocr-nginx:latest ./nginx

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start all services for testing
        run: |
          docker compose up -d mongodb ocr backend
          sleep 5

      - name: Wait for backend to be ready
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:8000/ping; then
              echo "Backend is ready!"
              break
            fi
            echo "Waiting for backend..."
            sleep 3
          done

      - name: Install dependencies and run tests
        run: |
          cd backend
          pip install -r requirements.txt
          pip install pytest
          pytest tests/test_ping.py

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy with Docker Compose
        run: |
          docker compose down
          docker compose up -d --build